### PR TITLE
got a fresh fac for ya

### PR DESCRIPTION
**Pull request by win9x-se**

### CODE REVIEW

**Comment by kriegisrei** [comment]
win9x homebrew helper gets security updates
how

**Comment by PhazonicRidley** [comment]
daily reminder yall should add a way to add facs dynamically

**Comment by PhazonicRidley** [comment]
also krieg is asuka, not rei

**Comment by melomori** [comment]
fuck your facts
krieg for helper

**Comment by win9x-se** [comment]
but the very next day

**Comment by kriegisrei** [comment]
my name is krieg, and i approve angel's message

**Pull request merged**
